### ISSUE TITLE
Gtk-WARNING **: cannot open display

### ISSUE THREAD

**Issue by amorenew** [kunfengchen/self-driving-car#1]
i downloaded it and open by Kitematic and clicked EXEC button then i write in popup console:
# cd ~/Autoware/ros
# ./run

Process Manager

(gksudo:51): Gtk-WARNING **: cannot open display:
error: XDG_RUNTIME_DIR not set in the environment.
Failed to parse arguments: Cannot open display:
error: XDG_RUNTIME_DIR not set in the environment.
Failed to parse arguments: Cannot open display:
# 

how could i fix this error ?
my os is windows 10 64bit

**Comment by amorenew** [comment]
may help you http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/

**Comment by jjdblast** [comment]
@amorenew Hi amorenew, I tried install vnc in my container, but how to run the whole pipeline ? What is the command you use to start container ?

**Comment by amorenew** [comment]
actually @jjdblast i didn't solve the problem yet and i closed the issue because windows not supported as owner said but i asked about external help in my spreadsheet
https://docs.google.com/spreadsheets/d/13QQinPFhU9DwujctXS0A7un0up4N5BNyUDZwxK4I6hg/edit#gid=0

**Comment by kunfengchen** [comment]
Try this link to see if that helps:
http://manomarks.github.io/2015/12/03/docker-gui-windows.html

I don't have a Windows to test X Display for Docker. Feedbacks will help others.
